### ISSUE TITLE
Could you provide some information about the reproduction of MAE-ViTBase in 100ep pretraining ?

### ISSUE THREAD

**Issue by HuangChiEn** [AbrahamYabo/SdAE#3]
Thanks for releasing this amazing work. 
We want to know some detail about the reproduction of MAE-ViTBase in 100ep if you don't mind.
Since the [repository](https://github.com/facebookresearch/mae) does not provide the configuration for pretraining MAE of ViTB version. How did you'll use the official code to reproduce the corresponding resutls.

We wonder **what configuration (or where to get it)** did you'll use to reproduce the 100ep finetuneing results of imageNet-1K based on **100-ep as well as 300-ep pretraining** ?

Any suggestion will be appreciated !!

**Comment by Cakeyan** [comment]
+1

**Comment by AbrahamYabo** [comment]
For 300-ep pretraining, you can follow the README.md. 
For 100-ep pretraining, trying:
python -m torch.distributed.launch --nproc_per_node 8 main_pretrain.py \
        --batch_size 96 --epochs 100 --model mae_vit_base_patch16 \
        --model_teacher vit_base_patch16 --data_path {DATA_DIR} --warmup_epochs 20 \
        --mask_ratio 0.75 --blr 2.666e-4 --ema_op per_epoch --ema_frequent 1 \
        --momentum_teacher 0.9 --momentum_teacher_final 0.95 \
        --drop_path 0.15 --shrink_num 147 --ncrop_loss 3

**Comment by HuangChiEn** [comment]
> For 300-ep pretraining, you can follow the README.md. For 100-ep pretraining, trying: python -m torch.distributed.launch --nproc_per_node 8 main_pretrain.py --batch_size 96 --epochs 100 --model mae_vit_base_patch16 --model_teacher vit_base_patch16 --data_path {DATA_DIR} --warmup_epochs 20 --mask_ratio 0.75 --blr 2.666e-4 --ema_op per_epoch --ema_frequent 1 --momentum_teacher 0.9 --momentum_teacher_final 0.95 --drop_path 0.15 --shrink_num 147 --ncrop_loss 3

Thanks for your configuration ~ 
now, close this issue ~

**Comment by Cakeyan** [comment]
Thanks a lot!
